# Generated by Django 5.2.8 on 2025-11-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CustomerID',
            new_name='id',
        ),
    ]
